/***********************
 * CUSTOM VARIABLES GENERATED BY VARIABLE BUILDER
 * Generated on: 15/10/2025, 12:15:23
 * Total variables: 8
 ***********************/

// Custom variables for use in alarm expressions and calculations
window.CUSTOM_VARIABLES = [
  { name: "Shock_index", expression: "SBP/HR", description: "Shock index" },
  { name: "API", expression: "(SBP - DBP) / PCWP", description: "Aortic Pulsatility Index" },
  { name: "RAP_PCWP_ratio", expression: "RAP / PCWP", description: "RAP/PCWP ratio" },
  { name: "Lactate", expression: "Lactate", description: "Serum lactate (mmol/L) - canonical name" },
  { name: "delta_lactate", expression: "delta_lactate", description: "Percent change in lactate vs previous timepoint (numeric percent)" },
  { name: "PulsePressure", expression: "SBP-DBP", description: "Pulse Pressure" },
  { name: "CPO_pct_change", expression: "(Delta(CPO) / Math.max(CPO - Delta(CPO), 1e-9)) * 100", description: "% change vs previous CPO" },
  { name: "CI_pct_change", expression: "(Delta(CI) / Math.max(CI - Delta(CI), 1e-9)) * 100", description: "% change vs previous CI" }
];

// Initialize custom variables when loaded
try {
  if (typeof initCustomVariables === 'function') {
    initCustomVariables();
  }
  // console.log removed: Custom variables loaded successfully
} catch(e) {
  console.error('Error loading custom variables:', e);
}